[platformio]
data_dir = $PROJECT_DIR/rootfs
src_dir = firmware

[env:adafruit_feather_nrf52840_sense]
platform = nordicnrf52
board = adafruit_feather_nrf52840_sense
framework = arduino

platform_packages =
   framework-arduinoadafruitnrf52 @ https://github.com/devicefuture/Adafruit_nRF52_Arduino.git

build_flags =
   -Iapps
   -DNRF52_S132
   -DconfigTIMER_TASK_PRIORITY=0
   -DLFS_FLASH_ADDR=0xB4000
   -DLFS_FLASH_TOTAL_SIZE=262144
   -DCATTO_USE_64_BIT
   -DCATTO_CUSTOM_PRINT_COMMAND

lib_deps =
    lib/catto/dist