#!/bin/bash

OVERWRITE=false

if [ "$1" = "--overwrite" ]; then
    OVERWRITE=true
fi

mkdir -p firmware/sysfs

> firmware/_sysfs.h
> firmware/_sysfs.cpp

tee -a firmware/_sysfs.h > /dev/null << EOF
// Autogenerated by \`sysfs.sh\`

#ifndef SYSFS_H_
#define SYSFS_H_

#include "datatypes.h"

EOF

tee -a firmware/_sysfs.cpp > /dev/null << EOF
// Autogenerated by \`sysfs.sh\`

#include <Arduino.h>

#include "_sysfs.h"
#include "fs.h"

bool sysfs::addFile(String path, const unsigned char* data, unsigned int length) {
    if (!fs::ensureParentDirectories(path)) {
        return false;
    }

    if (!$OVERWRITE && fs::exists(path)) {
        return true;
    }

    fs::FileHandle* file = fs::open(path, fs::FileMode::WRITE);

    if (!file) {
        return false;
    }

    file->write((const char*)data, length);

    delete file;

    Serial.print("Populated system file: ");
    Serial.println(path);

    return true;
}

bool sysfs::populate() {
EOF

for file in $(find rootfs -type f); do
    path=${file#rootfs/}
    id=${path//[\.\/]/_}

    xxd -n $id -i $file | sed -e "s/unsigned/inline unsigned/" > firmware/sysfs/$id.h

    echo "#include \"sysfs/$id.h\"" >> firmware/_sysfs.h
    echo "    if (!addFile(\"$path\", $id, ${id}_len)) {return false;}" >> firmware/_sysfs.cpp
done

tee -a firmware/_sysfs.h > /dev/null << EOF

namespace sysfs {
    bool addFile(String path, const unsigned char* data, unsigned int length);
    bool populate();
}

#endif
EOF

tee -a firmware/_sysfs.cpp > /dev/null << EOF

    return true;
}
EOF