// Autogenerated by `tools/api/builder.sh` using declarations from `tools/api/api.sh`

#include <Arduino.h>
#include <wasmu.h>

#include "_api.h"
#include "proc.h"
#include "datatypes.h"
#include "utils.h"
#include "proc.h"
#include "console.h"
#include "timing.h"
#include "rng.h"
#include "input.h"
#include "ui.h"
#include "fs.h"
#include "test.h"

dataTypes::List<api::StoredInstance> api::storedInstances;

template<typename T> T* api::getBySid(api::Type type, api::Sid sid) {
    StoredInstance* storedInstance = storedInstances[sid];

    if (!storedInstance || (storedInstance->type != type && !(
            (type == Type::timing_Time && storedInstance->type == Type::timing_EarthTime) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_Menu) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_ContextualMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_ContextualMenu) ||
            (type == Type::ui_ContextualMenu && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_Popup) ||
            (type == Type::ui_ContextualMenu && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_IntInput) ||
            (type == Type::test_TestClass && storedInstance->type == Type::test_TestSubclass) ||
        false
    ))) {
        Serial.println("Inheritance check failed");

        return new T(); // To ensure an object is always referenced
    }

    return (T*)storedInstance->instance;
}

api::Sid api::findOwnSid(void* instance) {
    storedInstances.start();

    unsigned int index = 0;

    while (auto storedInstance = storedInstances.next()) {
        if (storedInstance->instance == instance) {
            return index;
        }

        index++;
    }

    return -1;
}

template<typename T> api::Sid api::store(api::Type type, proc::Process* ownerProcess, T* instance) {
    StoredInstance* storedInstance = nullptr;
    bool foundEmptyStoredInstance = false;
    bool foundExistingStoredInstance = false;
    unsigned int index = 0;

    storedInstances.start();

    while ((storedInstance = storedInstances.next())) {
        if (storedInstance->type == Type::EMPTY) {
            foundEmptyStoredInstance = true;
            break;
        }

        if (instance && storedInstance->instance == instance) {
            foundExistingStoredInstance = true;
            break;
        }

        index++;
    }

    if (!storedInstance) {
        storedInstance = new StoredInstance();
    }

    storedInstance->type = type;
    storedInstance->ownerProcess = ownerProcess;
    storedInstance->instance = instance;

    if (foundEmptyStoredInstance || foundExistingStoredInstance) {
        return index;
    } else {
        return storedInstances.push(storedInstance) - 1;
    }
}

void deleteStoredInstance(api::StoredInstance* storedInstance) {
    if (!storedInstance || storedInstance->type == api::Type::EMPTY) {
        return;
    }

    switch (storedInstance->type) {
        case api::Type::Buffer: delete (dataTypes::Buffer*)storedInstance->instance; break;
        case api::Type::timing_Time: delete (timing::Time*)storedInstance->instance; break;
        case api::Type::timing_EarthTime: delete (timing::EarthTime*)storedInstance->instance; break;
        case api::Type::ui_Icon: delete (ui::Icon*)storedInstance->instance; break;
        case api::Type::ui_Screen: delete (ui::Screen*)storedInstance->instance; break;
        case api::Type::ui_Menu: delete (ui::Menu*)storedInstance->instance; break;
        case api::Type::ui_ContextualMenu: delete (ui::ContextualMenu*)storedInstance->instance; break;
        case api::Type::ui_ConfirmationMenu: delete (ui::ConfirmationMenu*)storedInstance->instance; break;
        case api::Type::ui_Popup: delete (ui::Popup*)storedInstance->instance; break;
        case api::Type::ui_TextInput: delete (ui::TextInput*)storedInstance->instance; break;
        case api::Type::ui_IntInput: delete (ui::IntInput*)storedInstance->instance; break;
        case api::Type::fs_FileHandle: delete (fs::FileHandle*)storedInstance->instance; break;
        case api::Type::fs_DirectoryListing: delete (fs::DirectoryListing*)storedInstance->instance; break;
        case api::Type::test_TestClass: delete (test::TestClass*)storedInstance->instance; break;
        case api::Type::test_TestSubclass: delete (test::TestSubclass*)storedInstance->instance; break;
        default: delete storedInstance->instance; break;
    }

    storedInstance->type = api::Type::EMPTY;
    storedInstance->ownerProcess = nullptr;
    storedInstance->instance = nullptr;
}

void api::deleteBySid(api::Sid sid) {
    deleteStoredInstance(storedInstances[sid]);
}

void api::deleteAllByOwnerProcess(proc::Process* ownerProcess) {
    storedInstances.start();

    while (auto storedInstance = storedInstances.next()) {
        if (storedInstance->type == Type::EMPTY || storedInstance->ownerProcess != ownerProcess) {
            continue;
        }

        deleteStoredInstance(storedInstance);
    }
}

int api::dc_getGlobalI32(wasmu_Context* context) {
    char* id = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    wasmu_TypedValue* global = wasmu_getExportedGlobal(context->activeModule, (wasmu_U8*)id);

    int result = global && global->type == WASMU_VALUE_TYPE_I32 ? global->value.asInt : 0;

    wasmu_pushInt(context, 4, result); wasmu_pushType(context, WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_deleteBySid(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::deleteBySid(_sid);

    return true;
}

int api::dc_sidIsNull(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    StoredInstance* storedInstance = api::storedInstances[_sid];

    wasmu_pushInt(context, 4, !storedInstance || !storedInstance->instance); wasmu_pushType(context, WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_getBufferSize(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<dataTypes::Buffer>(Type::Buffer, _sid)->getSize();

    wasmu_pushInt(context, 4, result); wasmu_pushType(context, WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_copyBufferInto(wasmu_Context* context) {
    char* destination = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    dataTypes::Buffer* buffer = api::getBySid<dataTypes::Buffer>(Type::Buffer, _sid);

    for (unsigned int i = 0; i < buffer->getSize(); i++) {
        destination[i] = buffer->data[i];
    }

    return true;
}

int api::dc_utils_longToString(wasmu_Context* context) {
    unsigned int base = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    long number = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(utils::longToString(number, base)));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_utils_unsignedLongToString(wasmu_Context* context) {
    unsigned int base = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned long number = (unsigned long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(utils::unsignedLongToString(number, base)));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_utils_doubleToString(wasmu_Context* context) {
    unsigned int decimalPlaces = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    double number = (double)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_F64)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_F64);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(utils::doubleToString(number, decimalPlaces)));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_utils_stringToLong(wasmu_Context* context) {
    unsigned int base = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    long result = utils::stringToLong(String(string), base);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_utils_stringToUnsignedLong(wasmu_Context* context) {
    unsigned int base = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned long result = utils::stringToUnsignedLong(String(string), base);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_utils_stringToDouble(wasmu_Context* context) {
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    double result = utils::stringToDouble(String(string));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_F64), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_F64);

    return true;
}

int api::dc_proc_stop(wasmu_Context* context) {
    proc::stop((proc::WasmProcess*)context->userData);

    return true;
}

int api::dc_console_logPart(wasmu_Context* context) {
    char* value = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, String(value));

    return true;
}

int api::dc_console_logPartChars(wasmu_Context* context) {
    char* value = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartUInt(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartInt(wasmu_Context* context) {
    int value = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartULong(wasmu_Context* context) {
    unsigned long value = (unsigned long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartLong(wasmu_Context* context) {
    long value = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartDouble(wasmu_Context* context) {
    double value = (double)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_F64)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_F64);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logPartPtr(wasmu_Context* context) {
    void* value = (void*)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    console::logPart((proc::WasmProcess*)context->userData, value);

    return true;
}

int api::dc_console_logNewline(wasmu_Context* context) {
    console::logNewline((proc::WasmProcess*)context->userData);

    return true;
}

int api::dc_timing_Time_new(wasmu_Context* context) {
    auto instance = new timing::Time();
    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_newUsingDate(wasmu_Context* context) {
    unsigned int second = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int minute = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int hour = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int day = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int year = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new timing::Time(year, month, day, hour, minute, second);
    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_newUsingMilliseconds(wasmu_Context* context) {
    unsigned long millisecondOfDay = (unsigned long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int day = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int year = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new timing::Time(year, month, day, millisecondOfDay);
    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_daysInYear(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->daysInYear();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_daysInMonth(wasmu_Context* context) {
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->daysInMonth(month);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_millisecondsInDay(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondsInDay();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_inLeapMillisecond(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->inLeapMillisecond();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_postLeapMillisecondOffset(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->postLeapMillisecondOffset();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_setDate(wasmu_Context* context) {
    unsigned int day = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int year = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->setDate(year, month, day);

    return true;
}

int api::dc_timing_Time_setTime(wasmu_Context* context) {
    unsigned int second = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int minute = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int hour = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->setTime(hour, minute, second);

    return true;
}

int api::dc_timing_Time_incrementTime(wasmu_Context* context) {
    int millseconds = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->incrementTime(millseconds);

    return true;
}

int api::dc_timing_Time_toLocalTime(wasmu_Context* context) {
    int timeShift = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->toLocalTime(timeShift);

    return true;
}

int api::dc_timing_Time_toGlobalTime(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->toGlobalTime();

    return true;
}

int api::dc_timing_Time_timeShift(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->timeShift();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_year(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->year();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_month(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->month();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_day(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->day();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_hour(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->hour();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_minute(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->minute();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_second(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->second();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_millisecond(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecond();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_dayOfYear(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->dayOfYear();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_millisecondOfDay(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondOfDay();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_millisecondOfDayIgnoringLeap(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondOfDayIgnoringLeap();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_Time_weekday(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->weekday();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_EarthTime_new(wasmu_Context* context) {
    auto instance = new timing::EarthTime();
    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_EarthTime_newUsingDate(wasmu_Context* context) {
    unsigned int second = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int minute = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int hour = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int day = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int year = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new timing::EarthTime(year, month, day, hour, minute, second);
    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_EarthTime_newUsingMilliseconds(wasmu_Context* context) {
    unsigned long millisecondOfDay = (unsigned long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int day = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int month = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int year = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new timing::EarthTime(year, month, day, millisecondOfDay);
    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_timing_EarthTime_syncToSystemTime(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<timing::EarthTime>(Type::timing_EarthTime, _sid)->syncToSystemTime();

    return true;
}

int api::dc_timing_getCurrentTick(wasmu_Context* context) {
    unsigned long result = timing::getCurrentTick();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_rng_getLongInRange(wasmu_Context* context) {
    long max = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    long min = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    long result = rng::getLongInRange(min, max);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_rng_getLong(wasmu_Context* context) {
    long result = rng::getLong();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_rng_getKey(wasmu_Context* context) {
    unsigned int length = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(rng::getKey(length)));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Icon_new(wasmu_Context* context) {
    auto instance = new ui::Icon();
    Sid result = api::store<ui::Icon>(Type::ui_Icon, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Icon_setPixel(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Icon>(Type::ui_Icon, _sid)->setPixel(x, y, (ui::PenMode)value);

    return true;
}

int api::dc_ui_Screen_new(wasmu_Context* context) {
    auto instance = new ui::Screen((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::Screen>(Type::ui_Screen, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Screen_clear(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->clear();

    return true;
}

int api::dc_ui_Screen_setPosition(wasmu_Context* context) {
    unsigned int row = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int column = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->setPosition(column, row);

    return true;
}

int api::dc_ui_Screen_setPixel(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->setPixel(x, y, (ui::PenMode)value);

    return true;
}

int api::dc_ui_Screen_printChar(wasmu_Context* context) {
    char c = (char)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(c);

    return true;
}

int api::dc_ui_Screen_print(wasmu_Context* context) {
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(String(string));

    return true;
}

int api::dc_ui_Screen_printChars(wasmu_Context* context) {
    char* chars = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(chars);

    return true;
}

int api::dc_ui_Screen_printUInt(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    return true;
}

int api::dc_ui_Screen_printInt(wasmu_Context* context) {
    int value = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    return true;
}

int api::dc_ui_Screen_printULong(wasmu_Context* context) {
    unsigned long value = (unsigned long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    return true;
}

int api::dc_ui_Screen_printLong(wasmu_Context* context) {
    long value = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    return true;
}

int api::dc_ui_Screen_printDouble(wasmu_Context* context) {
    double value = (double)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_F64)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_F64);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    return true;
}

int api::dc_ui_Screen_printIcon(wasmu_Context* context) {
    Sid icon = (Sid)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(api::getBySid<ui::Icon>(Type::ui_Icon, icon));

    return true;
}

int api::dc_ui_Screen_printRepeated(wasmu_Context* context) {
    unsigned int times = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->printRepeated(String(string), times);

    return true;
}

int api::dc_ui_Screen_scroll(wasmu_Context* context) {
    unsigned int maxLength = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->scroll(String(string), maxLength);

    return true;
}

int api::dc_ui_Screen_resetScroll(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->resetScroll();

    return true;
}

int api::dc_ui_Screen_pad(wasmu_Context* context) {
    char c = (char)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int size = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->pad(size, c);

    return true;
}

int api::dc_ui_Screen_rect(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y2 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x2 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y1 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x1 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->rect(x1, y1, x2, y2, (ui::PenMode)value);

    return true;
}

int api::dc_ui_Screen_filledRect(wasmu_Context* context) {
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y2 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x2 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int y1 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int x1 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->filledRect(x1, y1, x2, y2, (ui::PenMode)value);

    return true;
}

int api::dc_ui_Screen_open(wasmu_Context* context) {
    bool urgent = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->open(urgent);

    return true;
}

int api::dc_ui_Screen_close(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->close();

    return true;
}

int api::dc_ui_Screen_swapWith(wasmu_Context* context) {
    Sid currentScreen = (Sid)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->swapWith(api::getBySid<ui::Screen>(Type::ui_Screen, currentScreen));

    return true;
}

int api::dc_ui_Menu_new(wasmu_Context* context) {
    auto instance = new ui::Menu((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::Menu>(Type::ui_Menu, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Menu_clearItems(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->clearItems();

    return true;
}

int api::dc_ui_Menu_addItem(wasmu_Context* context) {
    char* item = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->addItem(String(item));

    return true;
}

int api::dc_ui_Menu_getCurrentIndex(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->getCurrentIndex();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Menu_setCurrentIndex(wasmu_Context* context) {
    unsigned int index = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->setCurrentIndex(index);

    return true;
}

int api::dc_ui_ContextualMenu_new(wasmu_Context* context) {
    auto instance = new ui::ContextualMenu((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::ContextualMenu>(Type::ui_ContextualMenu, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ContextualMenu_newWithTitle(wasmu_Context* context) {
    char* title = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new ui::ContextualMenu((proc::WasmProcess*)context->userData, String(title));
    Sid result = api::store<ui::ContextualMenu>(Type::ui_ContextualMenu, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ContextualMenu_getTitle(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->getTitle()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ContextualMenu_setTitle(wasmu_Context* context) {
    char* title = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->setTitle(String(title));

    return true;
}

int api::dc_ui_ContextualMenu_getSelectionBlinking(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->getSelectionBlinking();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ContextualMenu_setSelectionBlinking(wasmu_Context* context) {
    bool blinkSelection = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->setSelectionBlinking(blinkSelection);

    return true;
}

int api::dc_ui_ConfirmationMenu_new(wasmu_Context* context) {
    auto instance = new ui::ConfirmationMenu((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ConfirmationMenu_newWithTitle(wasmu_Context* context) {
    bool swapYesNo = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* title = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new ui::ConfirmationMenu((proc::WasmProcess*)context->userData, String(title), swapYesNo);
    Sid result = api::store<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_ConfirmationMenu_yesSelected(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, _sid)->yesSelected();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_Popup_new(wasmu_Context* context) {
    auto instance = new ui::Popup((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::Popup>(Type::ui_Popup, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_TextInput_new(wasmu_Context* context) {
    auto instance = new ui::TextInput((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::TextInput>(Type::ui_TextInput, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_TextInput_newWithValue(wasmu_Context* context) {
    char* value = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new ui::TextInput((proc::WasmProcess*)context->userData, String(value));
    Sid result = api::store<ui::TextInput>(Type::ui_TextInput, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_TextInput_getValue(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->getValue()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_TextInput_setValue(wasmu_Context* context) {
    char* value = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->setValue(String(value));

    return true;
}

int api::dc_ui_TextInput_typeTextChar(wasmu_Context* context) {
    char text = (char)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->typeText(text);

    return true;
}

int api::dc_ui_TextInput_typeText(wasmu_Context* context) {
    char* text = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->typeText(String(text));

    return true;
}

int api::dc_ui_TextInput_selectAll(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->selectAll();

    return true;
}

int api::dc_ui_IntInput_new(wasmu_Context* context) {
    auto instance = new ui::IntInput((proc::WasmProcess*)context->userData);
    Sid result = api::store<ui::IntInput>(Type::ui_IntInput, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_newWithTitleAndValue(wasmu_Context* context) {
    long value = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* title = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new ui::IntInput((proc::WasmProcess*)context->userData, String(title), value);
    Sid result = api::store<ui::IntInput>(Type::ui_IntInput, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_getTitle(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getTitle()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_setTitle(wasmu_Context* context) {
    char* title = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setTitle(String(title));

    return true;
}

int api::dc_ui_IntInput_getValue(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    long result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getValue();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_setValue(wasmu_Context* context) {
    long value = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setValue(value);

    return true;
}

int api::dc_ui_IntInput_getValueBlinking(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getValueBlinking();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_setValueBlinking(wasmu_Context* context) {
    bool blinkValue = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setValueBlinking(blinkValue);

    return true;
}

int api::dc_ui_IntInput_getBase(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getBase();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_ui_IntInput_setBase(wasmu_Context* context) {
    unsigned int base = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setBase(base);

    return true;
}

int api::dc_ui_IntInput_setRange(wasmu_Context* context) {
    long maxValue = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    long minValue = (long)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setRange(minValue, maxValue);

    return true;
}

int api::dc_fs_FileHandle_new(wasmu_Context* context) {
    auto instance = new fs::FileHandle((proc::WasmProcess*)context->userData);
    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_newWithPathAndMode(wasmu_Context* context) {
    unsigned int mode = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new fs::FileHandle((proc::WasmProcess*)context->userData, String(path), (fs::FileMode)mode);
    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_getPath(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getPath()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_getMode(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getMode();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_isOpen(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->isOpen();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_isAvailable(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->isAvailable();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_read(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    char result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->read();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_readString(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->readString()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_write(wasmu_Context* context) {
    char c = (char)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->write(c);

    return true;
}

int api::dc_fs_FileHandle_writeString(wasmu_Context* context) {
    char* string = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->write(String(string));

    return true;
}

int api::dc_fs_FileHandle_getSize(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getSize();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_tell(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->tell();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_FileHandle_seek(wasmu_Context* context) {
    unsigned int origins = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int position = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->seek(position, (fs::SeekOrigin)origins);

    return true;
}

int api::dc_fs_FileHandle_truncate(wasmu_Context* context) {
    unsigned int size = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->truncate(size);

    return true;
}

int api::dc_fs_FileHandle_start(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->start();

    return true;
}

int api::dc_fs_FileHandle_close(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->close();

    return true;
}

int api::dc_fs_DirectoryListing_new(wasmu_Context* context) {
    auto instance = new fs::DirectoryListing((proc::WasmProcess*)context->userData);
    Sid result = api::store<fs::DirectoryListing>(Type::fs_DirectoryListing, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_DirectoryListing_start(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<fs::DirectoryListing>(Type::fs_DirectoryListing, _sid)->start();

    return true;
}

int api::dc_fs_DirectoryListing_next(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<fs::DirectoryListing>(Type::fs_DirectoryListing, _sid)->next()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_DirectoryListing_length(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<fs::DirectoryListing>(Type::fs_DirectoryListing, _sid)->length();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_open(wasmu_Context* context) {
    unsigned int mode = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)context->userData, fs::open((proc::WasmProcess*)context->userData, String(path), (fs::FileMode)mode));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_isFileOpen(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::isFileOpen(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_exists(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::exists(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_getEntryType(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::getEntryType(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_remove(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::remove(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_rename(wasmu_Context* context) {
    char* newPath = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    char* oldPath = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::rename(String(oldPath), String(newPath));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_createDirectory(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::createDirectory(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_ensureParentDirectories(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = fs::ensureParentDirectories(String(path));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_fs_listDirectory(wasmu_Context* context) {
    char* path = (char*)wasmu_popPtr(context); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<fs::DirectoryListing>(Type::fs_DirectoryListing, (proc::WasmProcess*)context->userData, fs::listDirectory((proc::WasmProcess*)context->userData, String(path)));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_new(wasmu_Context* context) {
    unsigned int seed = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new test::TestClass(seed);
    Sid result = api::store<test::TestClass>(Type::test_TestClass, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_identify(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->identify();

    return true;
}

int api::dc_test_TestClass_add(wasmu_Context* context) {
    unsigned int value2 = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    unsigned int value = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->add(value, value2);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_bools(wasmu_Context* context) {
    bool c = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    bool b = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    bool a = (bool)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->bools(a, b, c);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_nextRandomNumber(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->nextRandomNumber();

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_getString(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->getString()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestClass_getChars(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)context->userData, new dataTypes::Buffer(api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->getChars()));

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestSubclass_new(wasmu_Context* context) {
    unsigned int seed = (unsigned int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    auto instance = new test::TestSubclass(seed);
    Sid result = api::store<test::TestSubclass>(Type::test_TestSubclass, (proc::WasmProcess*)context->userData, instance);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_TestSubclass_identify(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<test::TestSubclass>(Type::test_TestSubclass, _sid)->identify();

    return true;
}

int api::dc_test_TestSubclass_subclass(wasmu_Context* context) {
    Sid _sid = wasmu_popInt(context, 4); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    api::getBySid<test::TestSubclass>(Type::test_TestSubclass, _sid)->subclass();

    return true;
}

int api::dc_test_sayHello(wasmu_Context* context) {
    test::sayHello();

    return true;
}

int api::dc_test_add(wasmu_Context* context) {
    int b = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);
    int a = (int)wasmu_popInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32)); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    int result = test::add(a, b);

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

int api::dc_test_getMostRecentTest(wasmu_Context* context) {
    Sid result = api::store<test::TestClass>(Type::test_TestClass, (proc::WasmProcess*)context->userData, test::getMostRecentTest());

    wasmu_pushInt(context, wasmu_getValueTypeSize(WASMU_VALUE_TYPE_I32), result); WASMU_ASSERT_POP_TYPE(WASMU_VALUE_TYPE_I32);

    return true;
}

void api::linkFunctions(wasmu_Module* module) {
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_getGlobalI32", &dc_getGlobalI32);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_deleteBySid", &dc_deleteBySid);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_sidIsNull", &dc_sidIsNull);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_getBufferSize", &dc_getBufferSize);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_copyBufferInto", &dc_copyBufferInto);

    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_longToString", &dc_utils_longToString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_unsignedLongToString", &dc_utils_unsignedLongToString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_doubleToString", &dc_utils_doubleToString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_stringToLong", &dc_utils_stringToLong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_stringToUnsignedLong", &dc_utils_stringToUnsignedLong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_utils_stringToDouble", &dc_utils_stringToDouble);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_proc_stop", &dc_proc_stop);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPart", &dc_console_logPart);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartChars", &dc_console_logPartChars);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartUInt", &dc_console_logPartUInt);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartInt", &dc_console_logPartInt);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartULong", &dc_console_logPartULong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartLong", &dc_console_logPartLong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartDouble", &dc_console_logPartDouble);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logPartPtr", &dc_console_logPartPtr);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_console_logNewline", &dc_console_logNewline);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_new", &dc_timing_Time_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_newUsingDate", &dc_timing_Time_newUsingDate);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_newUsingMilliseconds", &dc_timing_Time_newUsingMilliseconds);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_daysInYear", &dc_timing_Time_daysInYear);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_daysInMonth", &dc_timing_Time_daysInMonth);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_millisecondsInDay", &dc_timing_Time_millisecondsInDay);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_inLeapMillisecond", &dc_timing_Time_inLeapMillisecond);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_postLeapMillisecondOffset", &dc_timing_Time_postLeapMillisecondOffset);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_setDate", &dc_timing_Time_setDate);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_setTime", &dc_timing_Time_setTime);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_incrementTime", &dc_timing_Time_incrementTime);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_toLocalTime", &dc_timing_Time_toLocalTime);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_toGlobalTime", &dc_timing_Time_toGlobalTime);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_timeShift", &dc_timing_Time_timeShift);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_year", &dc_timing_Time_year);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_month", &dc_timing_Time_month);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_day", &dc_timing_Time_day);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_hour", &dc_timing_Time_hour);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_minute", &dc_timing_Time_minute);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_second", &dc_timing_Time_second);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_millisecond", &dc_timing_Time_millisecond);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_dayOfYear", &dc_timing_Time_dayOfYear);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_millisecondOfDay", &dc_timing_Time_millisecondOfDay);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_millisecondOfDayIgnoringLeap", &dc_timing_Time_millisecondOfDayIgnoringLeap);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_Time_weekday", &dc_timing_Time_weekday);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_EarthTime_new", &dc_timing_EarthTime_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_EarthTime_newUsingDate", &dc_timing_EarthTime_newUsingDate);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_EarthTime_newUsingMilliseconds", &dc_timing_EarthTime_newUsingMilliseconds);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_EarthTime_syncToSystemTime", &dc_timing_EarthTime_syncToSystemTime);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_timing_getCurrentTick", &dc_timing_getCurrentTick);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_rng_getLongInRange", &dc_rng_getLongInRange);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_rng_getLong", &dc_rng_getLong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_rng_getKey", &dc_rng_getKey);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Icon_new", &dc_ui_Icon_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Icon_setPixel", &dc_ui_Icon_setPixel);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_new", &dc_ui_Screen_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_clear", &dc_ui_Screen_clear);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_setPosition", &dc_ui_Screen_setPosition);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_setPixel", &dc_ui_Screen_setPixel);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printChar", &dc_ui_Screen_printChar);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_print", &dc_ui_Screen_print);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printChars", &dc_ui_Screen_printChars);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printUInt", &dc_ui_Screen_printUInt);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printInt", &dc_ui_Screen_printInt);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printULong", &dc_ui_Screen_printULong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printLong", &dc_ui_Screen_printLong);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printDouble", &dc_ui_Screen_printDouble);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printIcon", &dc_ui_Screen_printIcon);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_printRepeated", &dc_ui_Screen_printRepeated);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_scroll", &dc_ui_Screen_scroll);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_resetScroll", &dc_ui_Screen_resetScroll);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_pad", &dc_ui_Screen_pad);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_rect", &dc_ui_Screen_rect);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_filledRect", &dc_ui_Screen_filledRect);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_open", &dc_ui_Screen_open);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_close", &dc_ui_Screen_close);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Screen_swapWith", &dc_ui_Screen_swapWith);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Menu_new", &dc_ui_Menu_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Menu_clearItems", &dc_ui_Menu_clearItems);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Menu_addItem", &dc_ui_Menu_addItem);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Menu_getCurrentIndex", &dc_ui_Menu_getCurrentIndex);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Menu_setCurrentIndex", &dc_ui_Menu_setCurrentIndex);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_new", &dc_ui_ContextualMenu_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_newWithTitle", &dc_ui_ContextualMenu_newWithTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_getTitle", &dc_ui_ContextualMenu_getTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_setTitle", &dc_ui_ContextualMenu_setTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_getSelectionBlinking", &dc_ui_ContextualMenu_getSelectionBlinking);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ContextualMenu_setSelectionBlinking", &dc_ui_ContextualMenu_setSelectionBlinking);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ConfirmationMenu_new", &dc_ui_ConfirmationMenu_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ConfirmationMenu_newWithTitle", &dc_ui_ConfirmationMenu_newWithTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_ConfirmationMenu_yesSelected", &dc_ui_ConfirmationMenu_yesSelected);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_Popup_new", &dc_ui_Popup_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_new", &dc_ui_TextInput_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_newWithValue", &dc_ui_TextInput_newWithValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_getValue", &dc_ui_TextInput_getValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_setValue", &dc_ui_TextInput_setValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_typeTextChar", &dc_ui_TextInput_typeTextChar);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_typeText", &dc_ui_TextInput_typeText);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_TextInput_selectAll", &dc_ui_TextInput_selectAll);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_new", &dc_ui_IntInput_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_newWithTitleAndValue", &dc_ui_IntInput_newWithTitleAndValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_getTitle", &dc_ui_IntInput_getTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_setTitle", &dc_ui_IntInput_setTitle);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_getValue", &dc_ui_IntInput_getValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_setValue", &dc_ui_IntInput_setValue);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_getValueBlinking", &dc_ui_IntInput_getValueBlinking);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_setValueBlinking", &dc_ui_IntInput_setValueBlinking);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_getBase", &dc_ui_IntInput_getBase);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_setBase", &dc_ui_IntInput_setBase);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_ui_IntInput_setRange", &dc_ui_IntInput_setRange);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_new", &dc_fs_FileHandle_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_newWithPathAndMode", &dc_fs_FileHandle_newWithPathAndMode);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_getPath", &dc_fs_FileHandle_getPath);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_getMode", &dc_fs_FileHandle_getMode);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_isOpen", &dc_fs_FileHandle_isOpen);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_isAvailable", &dc_fs_FileHandle_isAvailable);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_read", &dc_fs_FileHandle_read);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_readString", &dc_fs_FileHandle_readString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_write", &dc_fs_FileHandle_write);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_writeString", &dc_fs_FileHandle_writeString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_getSize", &dc_fs_FileHandle_getSize);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_tell", &dc_fs_FileHandle_tell);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_seek", &dc_fs_FileHandle_seek);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_truncate", &dc_fs_FileHandle_truncate);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_start", &dc_fs_FileHandle_start);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_FileHandle_close", &dc_fs_FileHandle_close);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_DirectoryListing_new", &dc_fs_DirectoryListing_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_DirectoryListing_start", &dc_fs_DirectoryListing_start);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_DirectoryListing_next", &dc_fs_DirectoryListing_next);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_DirectoryListing_length", &dc_fs_DirectoryListing_length);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_open", &dc_fs_open);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_isFileOpen", &dc_fs_isFileOpen);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_exists", &dc_fs_exists);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_getEntryType", &dc_fs_getEntryType);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_remove", &dc_fs_remove);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_rename", &dc_fs_rename);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_createDirectory", &dc_fs_createDirectory);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_ensureParentDirectories", &dc_fs_ensureParentDirectories);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_fs_listDirectory", &dc_fs_listDirectory);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_new", &dc_test_TestClass_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_identify", &dc_test_TestClass_identify);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_add", &dc_test_TestClass_add);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_bools", &dc_test_TestClass_bools);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_nextRandomNumber", &dc_test_TestClass_nextRandomNumber);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_getString", &dc_test_TestClass_getString);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestClass_getChars", &dc_test_TestClass_getChars);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestSubclass_new", &dc_test_TestSubclass_new);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestSubclass_identify", &dc_test_TestSubclass_identify);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_TestSubclass_subclass", &dc_test_TestSubclass_subclass);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_sayHello", &dc_test_sayHello);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_add", &dc_test_add);
    wasmu_addNativeFunction(module, (wasmu_U8*)"dc_test_getMostRecentTest", &dc_test_getMostRecentTest);
}
