// Autogenerated by `tools/api/builder.sh` using declarations from `tools/api/api.sh`

#include <Arduino.h>
#include <m3_env.h>

#include "_api.h"
#include "proc.h"
#include "datatypes.h"
#include "utils.h"
#include "proc.h"
#include "console.h"
#include "timing.h"
#include "input.h"
#include "ui.h"
#include "fs.h"
#include "test.h"

dataTypes::List<api::StoredInstance> api::storedInstances;

template<typename T> T* api::getBySid(api::Type type, api::Sid sid) {
    StoredInstance* storedInstance = storedInstances[sid];

    if (!storedInstance || (storedInstance->type != type && !(
            (type == Type::timing_Time && storedInstance->type == Type::timing_EarthTime) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_Menu) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_ContextualMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_ContextualMenu) ||
            (type == Type::ui_ContextualMenu && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_ConfirmationMenu) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_Popup) ||
            (type == Type::ui_ContextualMenu && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Menu && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_TextInput) ||
            (type == Type::ui_Screen && storedInstance->type == Type::ui_IntInput) ||
            (type == Type::test_TestClass && storedInstance->type == Type::test_TestSubclass) ||
        false
    ))) {
        Serial.println("Inheritance check failed");

        return new T(); // To ensure an object is always referenced
    }

    return (T*)storedInstance->instance;
}

api::Sid api::findOwnSid(void* instance) {
    storedInstances.start();

    unsigned int index = 0;

    while (auto storedInstance = storedInstances.next()) {
        if (storedInstance->instance == instance) {
            return index;
        }

        index++;
    }

    return -1;
}

template<typename T> api::Sid api::store(api::Type type, proc::Process* ownerProcess, T* instance) {
    StoredInstance* storedInstance = nullptr;
    bool foundEmptyStoredInstance = false;
    bool foundExistingStoredInstance = false;
    unsigned int index = 0;

    storedInstances.start();

    while ((storedInstance = storedInstances.next())) {
        if (storedInstance->type == Type::EMPTY) {
            foundEmptyStoredInstance = true;
            break;
        }

        if (instance && storedInstance->instance == instance) {
            foundExistingStoredInstance = true;
            break;
        }

        index++;
    }

    if (!storedInstance) {
        storedInstance = new StoredInstance();
    }

    storedInstance->type = type;
    storedInstance->ownerProcess = ownerProcess;
    storedInstance->instance = instance;

    if (foundEmptyStoredInstance || foundExistingStoredInstance) {
        return index;
    } else {
        return storedInstances.push(storedInstance) - 1;
    }
}

void deleteStoredInstance(api::StoredInstance* storedInstance) {
    if (!storedInstance || storedInstance->type == api::Type::EMPTY) {
        return;
    }

    switch (storedInstance->type) {
        case api::Type::Buffer: delete (dataTypes::Buffer*)storedInstance->instance; break;
        case api::Type::timing_Time: delete (timing::Time*)storedInstance->instance; break;
        case api::Type::timing_EarthTime: delete (timing::EarthTime*)storedInstance->instance; break;
        case api::Type::ui_Icon: delete (ui::Icon*)storedInstance->instance; break;
        case api::Type::ui_Screen: delete (ui::Screen*)storedInstance->instance; break;
        case api::Type::ui_Menu: delete (ui::Menu*)storedInstance->instance; break;
        case api::Type::ui_ContextualMenu: delete (ui::ContextualMenu*)storedInstance->instance; break;
        case api::Type::ui_ConfirmationMenu: delete (ui::ConfirmationMenu*)storedInstance->instance; break;
        case api::Type::ui_Popup: delete (ui::Popup*)storedInstance->instance; break;
        case api::Type::ui_TextInput: delete (ui::TextInput*)storedInstance->instance; break;
        case api::Type::ui_IntInput: delete (ui::IntInput*)storedInstance->instance; break;
        case api::Type::fs_FileHandle: delete (fs::FileHandle*)storedInstance->instance; break;
        case api::Type::test_TestClass: delete (test::TestClass*)storedInstance->instance; break;
        case api::Type::test_TestSubclass: delete (test::TestSubclass*)storedInstance->instance; break;
        default: delete storedInstance->instance; break;
    }

    storedInstance->type = api::Type::EMPTY;
    storedInstance->ownerProcess = nullptr;
    storedInstance->instance = nullptr;
}

void api::deleteBySid(api::Sid sid) {
    deleteStoredInstance(storedInstances[sid]);
}

void api::deleteAllByOwnerProcess(proc::Process* ownerProcess) {
    storedInstances.start();

    while (auto storedInstance = storedInstances.next()) {
        if (storedInstance->type == Type::EMPTY || storedInstance->ownerProcess != ownerProcess) {
            continue;
        }

        deleteStoredInstance(storedInstance);
    }
}

m3ApiRawFunction(api::dc_getGlobalI32) {
    m3ApiReturnType(uint32_t)
    m3ApiGetArgMem(char*, id)

    IM3Global global = m3_FindGlobal(runtime->modules, id);

    if (global) {
        M3TaggedValue globalValue;

        m3_GetGlobal(global, &globalValue);

        m3ApiReturn(globalValue.value.i32);
    } else {
        m3ApiReturn(0);
    }
}

m3ApiRawFunction(api::dc_deleteBySid) {
    m3ApiGetArg(Sid, _sid)

    api::deleteBySid(_sid);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_getBufferSize) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<dataTypes::Buffer>(Type::Buffer, _sid)->getSize();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_copyBufferInto) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, destination)

    dataTypes::Buffer* buffer = api::getBySid<dataTypes::Buffer>(Type::Buffer, _sid);

    for (unsigned int i = 0; i < buffer->getSize(); i++) {
        destination[i] = buffer->data[i];
    }

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_utils_numberToStringUInt) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(unsigned int, number)
    m3ApiGetArg(unsigned int, base)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(utils::numberToString(number, base)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_numberToStringInt) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(int, number)
    m3ApiGetArg(unsigned int, base)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(utils::numberToString(number, base)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_numberToStringULong) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(unsigned long, number)
    m3ApiGetArg(unsigned int, base)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(utils::numberToString(number, base)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_numberToStringLong) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(long, number)
    m3ApiGetArg(unsigned int, base)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(utils::numberToString(number, base)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_numberToStringDouble) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(double, number)
    m3ApiGetArg(unsigned int, base)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(utils::numberToString(number, base)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_stringToLong) {
    m3ApiReturnType(long)
    m3ApiGetArgMem(char*, string)

    long result = utils::stringToLong(String(string));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_utils_stringToDouble) {
    m3ApiReturnType(double)
    m3ApiGetArgMem(char*, string)

    double result = utils::stringToDouble(String(string));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_proc_stop) {
    proc::stop((proc::WasmProcess*)runtime->userdata);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPart) {
    m3ApiGetArgMem(char*, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, String(value));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartChars) {
    m3ApiGetArgMem(char*, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartUInt) {
    m3ApiGetArg(unsigned int, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartInt) {
    m3ApiGetArg(int, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartULong) {
    m3ApiGetArg(unsigned long, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartLong) {
    m3ApiGetArg(long, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartDouble) {
    m3ApiGetArg(double, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logPartPtr) {
    m3ApiGetArg(void*, value)

    console::logPart((proc::WasmProcess*)runtime->userdata, value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_console_logNewline) {
    console::logNewline((proc::WasmProcess*)runtime->userdata);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_new) {
    m3ApiReturnType(Sid)

    auto instance = new timing::Time();

    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_newUsingDate) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(int, year)
    m3ApiGetArg(unsigned int, month)
    m3ApiGetArg(unsigned int, day)
    m3ApiGetArg(unsigned int, hour)
    m3ApiGetArg(unsigned int, minute)
    m3ApiGetArg(unsigned int, second)

    auto instance = new timing::Time(year, month, day, hour, minute, second);

    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_newUsingMilliseconds) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(int, year)
    m3ApiGetArg(unsigned int, month)
    m3ApiGetArg(unsigned int, day)
    m3ApiGetArg(unsigned long, millisecondOfDay)

    auto instance = new timing::Time(year, month, day, millisecondOfDay);

    Sid result = api::store<timing::Time>(Type::timing_Time, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_daysInYear) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->daysInYear();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_daysInMonth) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, month)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->daysInMonth(month);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_millisecondsInDay) {
    m3ApiReturnType(unsigned long)
    m3ApiGetArg(Sid, _sid)

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondsInDay();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_inLeapMillisecond) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->inLeapMillisecond();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_postLeapMillisecondOffset) {
    m3ApiReturnType(unsigned long)
    m3ApiGetArg(Sid, _sid)

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->postLeapMillisecondOffset();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_setDate) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(int, year)
    m3ApiGetArg(unsigned int, month)
    m3ApiGetArg(unsigned int, day)

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->setDate(year, month, day);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_setTime) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, hour)
    m3ApiGetArg(unsigned int, minute)
    m3ApiGetArg(unsigned int, second)

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->setTime(hour, minute, second);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_incrementTime) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(int, millseconds)

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->incrementTime(millseconds);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_toLocalTime) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(int, timeShift)

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->toLocalTime(timeShift);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_toGlobalTime) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<timing::Time>(Type::timing_Time, _sid)->toGlobalTime();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_Time_timeShift) {
    m3ApiReturnType(int)
    m3ApiGetArg(Sid, _sid)

    int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->timeShift();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_year) {
    m3ApiReturnType(int)
    m3ApiGetArg(Sid, _sid)

    int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->year();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_month) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->month();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_day) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->day();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_hour) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->hour();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_minute) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->minute();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_second) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->second();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_millisecond) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecond();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_dayOfYear) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->dayOfYear();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_millisecondOfDay) {
    m3ApiReturnType(unsigned long)
    m3ApiGetArg(Sid, _sid)

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondOfDay();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_millisecondOfDayIgnoringLeap) {
    m3ApiReturnType(unsigned long)
    m3ApiGetArg(Sid, _sid)

    unsigned long result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->millisecondOfDayIgnoringLeap();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_Time_weekday) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<timing::Time>(Type::timing_Time, _sid)->weekday();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_EarthTime_new) {
    m3ApiReturnType(Sid)

    auto instance = new timing::EarthTime();

    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_EarthTime_newUsingDate) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(int, year)
    m3ApiGetArg(unsigned int, month)
    m3ApiGetArg(unsigned int, day)
    m3ApiGetArg(unsigned int, hour)
    m3ApiGetArg(unsigned int, minute)
    m3ApiGetArg(unsigned int, second)

    auto instance = new timing::EarthTime(year, month, day, hour, minute, second);

    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_EarthTime_newUsingMilliseconds) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(int, year)
    m3ApiGetArg(unsigned int, month)
    m3ApiGetArg(unsigned int, day)
    m3ApiGetArg(unsigned long, millisecondOfDay)

    auto instance = new timing::EarthTime(year, month, day, millisecondOfDay);

    Sid result = api::store<timing::EarthTime>(Type::timing_EarthTime, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_timing_EarthTime_syncToSystemTime) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<timing::EarthTime>(Type::timing_EarthTime, _sid)->syncToSystemTime();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_timing_getCurrentTick) {
    m3ApiReturnType(unsigned long)
    unsigned long result = timing::getCurrentTick();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Icon_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::Icon();

    Sid result = api::store<ui::Icon>(Type::ui_Icon, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Icon_setPixel) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, x)
    m3ApiGetArg(unsigned int, y)
    m3ApiGetArg(unsigned int, value)

    api::getBySid<ui::Icon>(Type::ui_Icon, _sid)->setPixel(x, y, (ui::PenMode)value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::Screen((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::Screen>(Type::ui_Screen, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Screen_clear) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->clear();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_setPosition) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, column)
    m3ApiGetArg(unsigned int, row)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->setPosition(column, row);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_setPixel) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, x)
    m3ApiGetArg(unsigned int, y)
    m3ApiGetArg(unsigned int, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->setPixel(x, y, (ui::PenMode)value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printChar) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(char, c)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(c);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_print) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, string)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(String(string));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printChars) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, chars)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(chars);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printUInt) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printInt) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(int, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printULong) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned long, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printLong) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(long, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printDouble) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(double, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printIcon) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(Sid, icon)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->print(api::getBySid<ui::Icon>(Type::ui_Icon, icon));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_printRepeated) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, string)
    m3ApiGetArg(unsigned int, times)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->printRepeated(String(string), times);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_scroll) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, string)
    m3ApiGetArg(unsigned int, maxLength)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->scroll(String(string), maxLength);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_resetScroll) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->resetScroll();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_pad) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, size)
    m3ApiGetArg(char, c)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->pad(size, c);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_rect) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, x1)
    m3ApiGetArg(unsigned int, y1)
    m3ApiGetArg(unsigned int, x2)
    m3ApiGetArg(unsigned int, y2)
    m3ApiGetArg(unsigned int, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->rect(x1, y1, x2, y2, (ui::PenMode)value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_filledRect) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, x1)
    m3ApiGetArg(unsigned int, y1)
    m3ApiGetArg(unsigned int, x2)
    m3ApiGetArg(unsigned int, y2)
    m3ApiGetArg(unsigned int, value)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->filledRect(x1, y1, x2, y2, (ui::PenMode)value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_open) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(bool, urgent)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->open(urgent);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_close) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->close();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Screen_swapWith) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(Sid, currentScreen)

    api::getBySid<ui::Screen>(Type::ui_Screen, _sid)->swapWith(api::getBySid<ui::Screen>(Type::ui_Screen, currentScreen));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Menu_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::Menu((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::Menu>(Type::ui_Menu, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Menu_clearItems) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->clearItems();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Menu_addItem) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, item)

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->addItem(String(item));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_Menu_getCurrentIndex) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->getCurrentIndex();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Menu_setCurrentIndex) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, index)

    api::getBySid<ui::Menu>(Type::ui_Menu, _sid)->setCurrentIndex(index);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::ContextualMenu((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::ContextualMenu>(Type::ui_ContextualMenu, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_newWithTitle) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, title)

    auto instance = new ui::ContextualMenu((proc::WasmProcess*)runtime->userdata, String(title));

    Sid result = api::store<ui::ContextualMenu>(Type::ui_ContextualMenu, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_getTitle) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->getTitle()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_setTitle) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, title)

    api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->setTitle(String(title));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_getSelectionBlinking) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->getSelectionBlinking();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ContextualMenu_setSelectionBlinking) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(bool, blinkSelection)

    api::getBySid<ui::ContextualMenu>(Type::ui_ContextualMenu, _sid)->setSelectionBlinking(blinkSelection);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_ConfirmationMenu_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::ConfirmationMenu((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ConfirmationMenu_newWithTitle) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, title)
    m3ApiGetArg(bool, swapYesNo)

    auto instance = new ui::ConfirmationMenu((proc::WasmProcess*)runtime->userdata, String(title), swapYesNo);

    Sid result = api::store<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_ConfirmationMenu_yesSelected) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<ui::ConfirmationMenu>(Type::ui_ConfirmationMenu, _sid)->yesSelected();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_Popup_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::Popup((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::Popup>(Type::ui_Popup, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_TextInput_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::TextInput((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::TextInput>(Type::ui_TextInput, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_TextInput_newWithValue) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, value)

    auto instance = new ui::TextInput((proc::WasmProcess*)runtime->userdata, String(value));

    Sid result = api::store<ui::TextInput>(Type::ui_TextInput, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_TextInput_getValue) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->getValue()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_TextInput_setValue) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, value)

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->setValue(String(value));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_TextInput_typeTextChar) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(char, text)

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->typeText(text);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_TextInput_typeText) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, text)

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->typeText(String(text));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_TextInput_selectAll) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<ui::TextInput>(Type::ui_TextInput, _sid)->selectAll();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_IntInput_new) {
    m3ApiReturnType(Sid)

    auto instance = new ui::IntInput((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<ui::IntInput>(Type::ui_IntInput, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_TextInput_newWithTitleAndValue) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, title)
    m3ApiGetArg(long, value)

    auto instance = new ui::IntInput((proc::WasmProcess*)runtime->userdata, String(title), value);

    Sid result = api::store<ui::IntInput>(Type::ui_IntInput, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_IntInput_getTitle) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getTitle()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_IntInput_setTitle) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, title)

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setTitle(String(title));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_IntInput_getValue) {
    m3ApiReturnType(long)
    m3ApiGetArg(Sid, _sid)

    long result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getValue();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_IntInput_setValue) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(long, value)

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setValue(value);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_IntInput_getValueBlinking) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getValueBlinking();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_IntInput_setValueBlinking) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(bool, blinkValue)

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setValueBlinking(blinkValue);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_IntInput_getBase) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->getBase();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_ui_IntInput_setBase) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, base)

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setBase(base);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_ui_IntInput_setRange) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(long, minValue)
    m3ApiGetArg(long, maxValue)

    api::getBySid<ui::IntInput>(Type::ui_IntInput, _sid)->setRange(minValue, maxValue);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_new) {
    m3ApiReturnType(Sid)

    auto instance = new fs::FileHandle((proc::WasmProcess*)runtime->userdata);

    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_newWithPathAndMode) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, path)
    m3ApiGetArg(unsigned int, mode)

    auto instance = new fs::FileHandle((proc::WasmProcess*)runtime->userdata, String(path), (fs::FileMode)mode);

    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_getPath) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getPath()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_getMode) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getMode();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_isOpen) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->isOpen();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_isAvailable) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->isAvailable();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_read) {
    m3ApiReturnType(char)
    m3ApiGetArg(Sid, _sid)

    char result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->read();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_readString) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->readString()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_readChars) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->readChars()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_write) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(char, c)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->write(c);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_writeString) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, string)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->write(String(string));

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_writeChars) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArgMem(char*, chars)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->write(chars);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_getSize) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->getSize();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_tell) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->tell();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_FileHandle_seek) {
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(int, position)
    m3ApiGetArg(unsigned int, origins)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->seek(position, (fs::SeekOrigin)origins);

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_start) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->start();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_FileHandle_close) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<fs::FileHandle>(Type::fs_FileHandle, _sid)->close();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_fs_open) {
    m3ApiReturnType(Sid)
    m3ApiGetArgMem(char*, path)
    m3ApiGetArg(unsigned int, mode)

    Sid result = api::store<fs::FileHandle>(Type::fs_FileHandle, (proc::WasmProcess*)runtime->userdata, fs::open(String(path), (fs::FileMode)mode));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_getFileModeString) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(unsigned int, mode)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(fs::getFileModeString((fs::FileMode)mode)));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_fs_isFileOpen) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArgMem(char*, path)

    unsigned int result = fs::isFileOpen(String(path));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_new) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(unsigned int, seed)

    auto instance = new test::TestClass(seed);

    Sid result = api::store<test::TestClass>(Type::test_TestClass, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_identify) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->identify();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_test_TestClass_add) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(unsigned int, value)
    m3ApiGetArg(unsigned int, value2)

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->add(value, value2);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_bools) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)
    m3ApiGetArg(bool, a)
    m3ApiGetArg(bool, b)
    m3ApiGetArg(bool, c)

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->bools(a, b, c);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_nextRandomNumber) {
    m3ApiReturnType(unsigned int)
    m3ApiGetArg(Sid, _sid)

    unsigned int result = api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->nextRandomNumber();

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_getString) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->getString()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestClass_getChars) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(Sid, _sid)

    Sid result = api::store<dataTypes::Buffer>(Type::Buffer, (proc::WasmProcess*)runtime->userdata, new dataTypes::Buffer(api::getBySid<test::TestClass>(Type::test_TestClass, _sid)->getChars()));

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestSubclass_new) {
    m3ApiReturnType(Sid)
    m3ApiGetArg(unsigned int, seed)

    auto instance = new test::TestSubclass(seed);

    Sid result = api::store<test::TestSubclass>(Type::test_TestSubclass, (proc::WasmProcess*)runtime->userdata, instance);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_TestSubclass_identify) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<test::TestSubclass>(Type::test_TestSubclass, _sid)->identify();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_test_TestSubclass_subclass) {
    m3ApiGetArg(Sid, _sid)

    api::getBySid<test::TestSubclass>(Type::test_TestSubclass, _sid)->subclass();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_test_sayHello) {
    test::sayHello();

    m3ApiSuccess();
}

m3ApiRawFunction(api::dc_test_add) {
    m3ApiReturnType(int)
    m3ApiGetArg(int, a)
    m3ApiGetArg(int, b)

    int result = test::add(a, b);

    m3ApiReturn(result);
}

m3ApiRawFunction(api::dc_test_getMostRecentTest) {
    m3ApiReturnType(Sid)

    Sid result = api::store<test::TestClass>(Type::test_TestClass, (proc::WasmProcess*)runtime->userdata, test::getMostRecentTest());

    m3ApiReturn(result);
}

void api::linkFunctions(IM3Runtime runtime) {
    const char* MODULE_NAME = "digicron";

    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_getGlobalI32", "i(*)", &dc_getGlobalI32);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_deleteBySid", "v(i)", &dc_deleteBySid);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_getBufferSize", "i(i)", &dc_getBufferSize);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_copyBufferInto", "v(i*)", &dc_copyBufferInto);

    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_numberToStringUInt", "i(ii)", &dc_utils_numberToStringUInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_numberToStringInt", "i(ii)", &dc_utils_numberToStringInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_numberToStringULong", "i(ii)", &dc_utils_numberToStringULong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_numberToStringLong", "i(ii)", &dc_utils_numberToStringLong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_numberToStringDouble", "i(Fi)", &dc_utils_numberToStringDouble);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_stringToLong", "i(i)", &dc_utils_stringToLong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_utils_stringToDouble", "i(i)", &dc_utils_stringToDouble);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_proc_stop", "v()", &dc_proc_stop);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPart", "v(i)", &dc_console_logPart);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartChars", "v(*)", &dc_console_logPartChars);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartUInt", "v(i)", &dc_console_logPartUInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartInt", "v(i)", &dc_console_logPartInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartULong", "v(i)", &dc_console_logPartULong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartLong", "v(i)", &dc_console_logPartLong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartDouble", "v(F)", &dc_console_logPartDouble);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logPartPtr", "v(*)", &dc_console_logPartPtr);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_console_logNewline", "v()", &dc_console_logNewline);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_new", "i()", &dc_timing_Time_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_newUsingDate", "i(iiiiii)", &dc_timing_Time_newUsingDate);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_newUsingMilliseconds", "i(iiii)", &dc_timing_Time_newUsingMilliseconds);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_daysInYear", "i(i)", &dc_timing_Time_daysInYear);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_daysInMonth", "i(ii)", &dc_timing_Time_daysInMonth);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_millisecondsInDay", "i(i)", &dc_timing_Time_millisecondsInDay);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_inLeapMillisecond", "i(i)", &dc_timing_Time_inLeapMillisecond);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_postLeapMillisecondOffset", "i(i)", &dc_timing_Time_postLeapMillisecondOffset);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_setDate", "v(iiii)", &dc_timing_Time_setDate);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_setTime", "v(iiii)", &dc_timing_Time_setTime);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_incrementTime", "v(ii)", &dc_timing_Time_incrementTime);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_toLocalTime", "v(ii)", &dc_timing_Time_toLocalTime);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_toGlobalTime", "v(i)", &dc_timing_Time_toGlobalTime);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_timeShift", "i(i)", &dc_timing_Time_timeShift);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_year", "i(i)", &dc_timing_Time_year);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_month", "i(i)", &dc_timing_Time_month);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_day", "i(i)", &dc_timing_Time_day);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_hour", "i(i)", &dc_timing_Time_hour);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_minute", "i(i)", &dc_timing_Time_minute);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_second", "i(i)", &dc_timing_Time_second);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_millisecond", "i(i)", &dc_timing_Time_millisecond);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_dayOfYear", "i(i)", &dc_timing_Time_dayOfYear);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_millisecondOfDay", "i(i)", &dc_timing_Time_millisecondOfDay);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_millisecondOfDayIgnoringLeap", "i(i)", &dc_timing_Time_millisecondOfDayIgnoringLeap);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_Time_weekday", "i(i)", &dc_timing_Time_weekday);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_EarthTime_new", "i()", &dc_timing_EarthTime_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_EarthTime_newUsingDate", "i(iiiiii)", &dc_timing_EarthTime_newUsingDate);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_EarthTime_newUsingMilliseconds", "i(iiii)", &dc_timing_EarthTime_newUsingMilliseconds);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_EarthTime_syncToSystemTime", "v(i)", &dc_timing_EarthTime_syncToSystemTime);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_timing_getCurrentTick", "i()", &dc_timing_getCurrentTick);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Icon_new", "i()", &dc_ui_Icon_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Icon_setPixel", "v(iiii)", &dc_ui_Icon_setPixel);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_new", "i()", &dc_ui_Screen_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_clear", "v(i)", &dc_ui_Screen_clear);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_setPosition", "v(iii)", &dc_ui_Screen_setPosition);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_setPixel", "v(iiii)", &dc_ui_Screen_setPixel);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printChar", "v(ii)", &dc_ui_Screen_printChar);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_print", "v(ii)", &dc_ui_Screen_print);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printChars", "v(i*)", &dc_ui_Screen_printChars);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printUInt", "v(ii)", &dc_ui_Screen_printUInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printInt", "v(ii)", &dc_ui_Screen_printInt);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printULong", "v(ii)", &dc_ui_Screen_printULong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printLong", "v(ii)", &dc_ui_Screen_printLong);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printDouble", "v(iF)", &dc_ui_Screen_printDouble);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printIcon", "v(ii)", &dc_ui_Screen_printIcon);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_printRepeated", "v(iii)", &dc_ui_Screen_printRepeated);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_scroll", "v(iii)", &dc_ui_Screen_scroll);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_resetScroll", "v(i)", &dc_ui_Screen_resetScroll);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_pad", "v(iii)", &dc_ui_Screen_pad);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_rect", "v(iiiiii)", &dc_ui_Screen_rect);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_filledRect", "v(iiiiii)", &dc_ui_Screen_filledRect);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_open", "v(ii)", &dc_ui_Screen_open);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_close", "v(i)", &dc_ui_Screen_close);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Screen_swapWith", "v(ii)", &dc_ui_Screen_swapWith);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Menu_new", "i()", &dc_ui_Menu_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Menu_clearItems", "v(i)", &dc_ui_Menu_clearItems);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Menu_addItem", "v(ii)", &dc_ui_Menu_addItem);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Menu_getCurrentIndex", "i(i)", &dc_ui_Menu_getCurrentIndex);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Menu_setCurrentIndex", "v(ii)", &dc_ui_Menu_setCurrentIndex);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_new", "i()", &dc_ui_ContextualMenu_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_newWithTitle", "i(i)", &dc_ui_ContextualMenu_newWithTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_getTitle", "i(i)", &dc_ui_ContextualMenu_getTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_setTitle", "v(ii)", &dc_ui_ContextualMenu_setTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_getSelectionBlinking", "i(i)", &dc_ui_ContextualMenu_getSelectionBlinking);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ContextualMenu_setSelectionBlinking", "v(ii)", &dc_ui_ContextualMenu_setSelectionBlinking);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ConfirmationMenu_new", "i()", &dc_ui_ConfirmationMenu_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ConfirmationMenu_newWithTitle", "i(ii)", &dc_ui_ConfirmationMenu_newWithTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_ConfirmationMenu_yesSelected", "i(i)", &dc_ui_ConfirmationMenu_yesSelected);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_Popup_new", "i()", &dc_ui_Popup_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_new", "i()", &dc_ui_TextInput_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_newWithValue", "i(i)", &dc_ui_TextInput_newWithValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_getValue", "i(i)", &dc_ui_TextInput_getValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_setValue", "v(ii)", &dc_ui_TextInput_setValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_typeTextChar", "v(ii)", &dc_ui_TextInput_typeTextChar);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_typeText", "v(ii)", &dc_ui_TextInput_typeText);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_selectAll", "v(i)", &dc_ui_TextInput_selectAll);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_new", "i()", &dc_ui_IntInput_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_TextInput_newWithTitleAndValue", "i(ii)", &dc_ui_TextInput_newWithTitleAndValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_getTitle", "i(i)", &dc_ui_IntInput_getTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_setTitle", "v(ii)", &dc_ui_IntInput_setTitle);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_getValue", "i(i)", &dc_ui_IntInput_getValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_setValue", "v(ii)", &dc_ui_IntInput_setValue);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_getValueBlinking", "i(i)", &dc_ui_IntInput_getValueBlinking);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_setValueBlinking", "v(ii)", &dc_ui_IntInput_setValueBlinking);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_getBase", "i(i)", &dc_ui_IntInput_getBase);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_setBase", "v(ii)", &dc_ui_IntInput_setBase);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_ui_IntInput_setRange", "v(iii)", &dc_ui_IntInput_setRange);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_new", "i()", &dc_fs_FileHandle_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_newWithPathAndMode", "i(ii)", &dc_fs_FileHandle_newWithPathAndMode);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_getPath", "i(i)", &dc_fs_FileHandle_getPath);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_getMode", "i(i)", &dc_fs_FileHandle_getMode);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_isOpen", "i(i)", &dc_fs_FileHandle_isOpen);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_isAvailable", "i(i)", &dc_fs_FileHandle_isAvailable);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_read", "i(i)", &dc_fs_FileHandle_read);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_readString", "i(i)", &dc_fs_FileHandle_readString);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_readChars", "i(i)", &dc_fs_FileHandle_readChars);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_write", "v(ii)", &dc_fs_FileHandle_write);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_writeString", "v(ii)", &dc_fs_FileHandle_writeString);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_writeChars", "v(i*)", &dc_fs_FileHandle_writeChars);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_getSize", "i(i)", &dc_fs_FileHandle_getSize);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_tell", "i(i)", &dc_fs_FileHandle_tell);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_seek", "v(iii)", &dc_fs_FileHandle_seek);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_start", "v(i)", &dc_fs_FileHandle_start);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_FileHandle_close", "v(i)", &dc_fs_FileHandle_close);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_open", "i(ii)", &dc_fs_open);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_getFileModeString", "i(i)", &dc_fs_getFileModeString);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_fs_isFileOpen", "i(i)", &dc_fs_isFileOpen);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_new", "i(i)", &dc_test_TestClass_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_identify", "v(i)", &dc_test_TestClass_identify);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_add", "i(iii)", &dc_test_TestClass_add);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_bools", "i(iiii)", &dc_test_TestClass_bools);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_nextRandomNumber", "i(i)", &dc_test_TestClass_nextRandomNumber);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_getString", "i(i)", &dc_test_TestClass_getString);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestClass_getChars", "i(i)", &dc_test_TestClass_getChars);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestSubclass_new", "i(i)", &dc_test_TestSubclass_new);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestSubclass_identify", "v(i)", &dc_test_TestSubclass_identify);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_TestSubclass_subclass", "v(i)", &dc_test_TestSubclass_subclass);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_sayHello", "v()", &dc_test_sayHello);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_add", "i(ii)", &dc_test_add);
    m3_LinkRawFunction(runtime->modules, MODULE_NAME, "dc_test_getMostRecentTest", "i()", &dc_test_getMostRecentTest);
}
