// Autogenerated by `tools/api/builder.sh` using declarations from `tools/api/api.sh`

#ifndef API_H_
#define API_H_

#include <wasmu.h>

#include "utils.h"
#include "proc.h"
#include "console.h"
#include "timing.h"
#include "rng.h"
#include "input.h"
#include "ui.h"
#include "fs.h"
#include "test.h"

namespace api {
    typedef int Sid;

    enum Type {EMPTY, Buffer, timing_Time, timing_EarthTime, ui_Icon, ui_Screen, ui_Menu, ui_ContextualMenu, ui_ConfirmationMenu, ui_Popup, ui_TextInput, ui_IntInput, fs_FileHandle, fs_DirectoryListing, test_TestClass, test_TestSubclass};

    struct StoredInstance {
        Type type;
        proc::Process* ownerProcess;
        void* instance;
    };

    extern dataTypes::List<StoredInstance> storedInstances;

    template<typename T> T* getBySid(Type type, Sid sid);
    Sid findOwnSid(void* instance);
    template<typename T> Sid store(Type type, proc::Process* ownerProcess, T* instance);
    void deleteBySid(Sid sid);
    void deleteAllByOwnerProcess(proc::Process* ownerProcess);

    int dc_getGlobalI32(wasmu_Context* context);
    int dc_deleteBySid(wasmu_Context* context);
    int dc_sidIsNull(wasmu_Context* context);
    int dc_getBufferSize(wasmu_Context* context);
    int dc_copyBufferInto(wasmu_Context* context);

    int dc_utils_longToString(wasmu_Context* context);
    int dc_utils_unsignedLongToString(wasmu_Context* context);
    int dc_utils_doubleToString(wasmu_Context* context);
    int dc_utils_stringToLong(wasmu_Context* context);
    int dc_utils_stringToUnsignedLong(wasmu_Context* context);
    int dc_utils_stringToDouble(wasmu_Context* context);
    int dc_proc_stop(wasmu_Context* context);
    int dc_console_logPart(wasmu_Context* context);
    int dc_console_logPartChars(wasmu_Context* context);
    int dc_console_logPartUInt(wasmu_Context* context);
    int dc_console_logPartInt(wasmu_Context* context);
    int dc_console_logPartULong(wasmu_Context* context);
    int dc_console_logPartLong(wasmu_Context* context);
    int dc_console_logPartDouble(wasmu_Context* context);
    int dc_console_logPartPtr(wasmu_Context* context);
    int dc_console_logNewline(wasmu_Context* context);
    int dc_timing_Time_new(wasmu_Context* context);
    int dc_timing_Time_newUsingDate(wasmu_Context* context);
    int dc_timing_Time_newUsingMilliseconds(wasmu_Context* context);
    int dc_timing_Time_daysInYear(wasmu_Context* context);
    int dc_timing_Time_daysInMonth(wasmu_Context* context);
    int dc_timing_Time_millisecondsInDay(wasmu_Context* context);
    int dc_timing_Time_inLeapMillisecond(wasmu_Context* context);
    int dc_timing_Time_postLeapMillisecondOffset(wasmu_Context* context);
    int dc_timing_Time_setDate(wasmu_Context* context);
    int dc_timing_Time_setTime(wasmu_Context* context);
    int dc_timing_Time_incrementTime(wasmu_Context* context);
    int dc_timing_Time_toLocalTime(wasmu_Context* context);
    int dc_timing_Time_toGlobalTime(wasmu_Context* context);
    int dc_timing_Time_timeShift(wasmu_Context* context);
    int dc_timing_Time_year(wasmu_Context* context);
    int dc_timing_Time_month(wasmu_Context* context);
    int dc_timing_Time_day(wasmu_Context* context);
    int dc_timing_Time_hour(wasmu_Context* context);
    int dc_timing_Time_minute(wasmu_Context* context);
    int dc_timing_Time_second(wasmu_Context* context);
    int dc_timing_Time_millisecond(wasmu_Context* context);
    int dc_timing_Time_dayOfYear(wasmu_Context* context);
    int dc_timing_Time_millisecondOfDay(wasmu_Context* context);
    int dc_timing_Time_millisecondOfDayIgnoringLeap(wasmu_Context* context);
    int dc_timing_Time_weekday(wasmu_Context* context);
    int dc_timing_EarthTime_new(wasmu_Context* context);
    int dc_timing_EarthTime_newUsingDate(wasmu_Context* context);
    int dc_timing_EarthTime_newUsingMilliseconds(wasmu_Context* context);
    int dc_timing_EarthTime_syncToSystemTime(wasmu_Context* context);
    int dc_timing_getCurrentTick(wasmu_Context* context);
    int dc_rng_getLongInRange(wasmu_Context* context);
    int dc_rng_getLong(wasmu_Context* context);
    int dc_rng_getKey(wasmu_Context* context);
    int dc_ui_Icon_new(wasmu_Context* context);
    int dc_ui_Icon_setPixel(wasmu_Context* context);
    int dc_ui_Screen_new(wasmu_Context* context);
    int dc_ui_Screen_clear(wasmu_Context* context);
    int dc_ui_Screen_setPosition(wasmu_Context* context);
    int dc_ui_Screen_setPixel(wasmu_Context* context);
    int dc_ui_Screen_printChar(wasmu_Context* context);
    int dc_ui_Screen_print(wasmu_Context* context);
    int dc_ui_Screen_printChars(wasmu_Context* context);
    int dc_ui_Screen_printUInt(wasmu_Context* context);
    int dc_ui_Screen_printInt(wasmu_Context* context);
    int dc_ui_Screen_printULong(wasmu_Context* context);
    int dc_ui_Screen_printLong(wasmu_Context* context);
    int dc_ui_Screen_printDouble(wasmu_Context* context);
    int dc_ui_Screen_printIcon(wasmu_Context* context);
    int dc_ui_Screen_printRepeated(wasmu_Context* context);
    int dc_ui_Screen_scroll(wasmu_Context* context);
    int dc_ui_Screen_resetScroll(wasmu_Context* context);
    int dc_ui_Screen_pad(wasmu_Context* context);
    int dc_ui_Screen_rect(wasmu_Context* context);
    int dc_ui_Screen_filledRect(wasmu_Context* context);
    int dc_ui_Screen_open(wasmu_Context* context);
    int dc_ui_Screen_close(wasmu_Context* context);
    int dc_ui_Screen_swapWith(wasmu_Context* context);
    int dc_ui_Menu_new(wasmu_Context* context);
    int dc_ui_Menu_clearItems(wasmu_Context* context);
    int dc_ui_Menu_addItem(wasmu_Context* context);
    int dc_ui_Menu_getCurrentIndex(wasmu_Context* context);
    int dc_ui_Menu_setCurrentIndex(wasmu_Context* context);
    int dc_ui_ContextualMenu_new(wasmu_Context* context);
    int dc_ui_ContextualMenu_newWithTitle(wasmu_Context* context);
    int dc_ui_ContextualMenu_getTitle(wasmu_Context* context);
    int dc_ui_ContextualMenu_setTitle(wasmu_Context* context);
    int dc_ui_ContextualMenu_getSelectionBlinking(wasmu_Context* context);
    int dc_ui_ContextualMenu_setSelectionBlinking(wasmu_Context* context);
    int dc_ui_ConfirmationMenu_new(wasmu_Context* context);
    int dc_ui_ConfirmationMenu_newWithTitle(wasmu_Context* context);
    int dc_ui_ConfirmationMenu_yesSelected(wasmu_Context* context);
    int dc_ui_Popup_new(wasmu_Context* context);
    int dc_ui_TextInput_new(wasmu_Context* context);
    int dc_ui_TextInput_newWithValue(wasmu_Context* context);
    int dc_ui_TextInput_getValue(wasmu_Context* context);
    int dc_ui_TextInput_setValue(wasmu_Context* context);
    int dc_ui_TextInput_typeTextChar(wasmu_Context* context);
    int dc_ui_TextInput_typeText(wasmu_Context* context);
    int dc_ui_TextInput_selectAll(wasmu_Context* context);
    int dc_ui_IntInput_new(wasmu_Context* context);
    int dc_ui_IntInput_newWithTitleAndValue(wasmu_Context* context);
    int dc_ui_IntInput_getTitle(wasmu_Context* context);
    int dc_ui_IntInput_setTitle(wasmu_Context* context);
    int dc_ui_IntInput_getValue(wasmu_Context* context);
    int dc_ui_IntInput_setValue(wasmu_Context* context);
    int dc_ui_IntInput_getValueBlinking(wasmu_Context* context);
    int dc_ui_IntInput_setValueBlinking(wasmu_Context* context);
    int dc_ui_IntInput_getBase(wasmu_Context* context);
    int dc_ui_IntInput_setBase(wasmu_Context* context);
    int dc_ui_IntInput_setRange(wasmu_Context* context);
    int dc_fs_FileHandle_new(wasmu_Context* context);
    int dc_fs_FileHandle_newWithPathAndMode(wasmu_Context* context);
    int dc_fs_FileHandle_getPath(wasmu_Context* context);
    int dc_fs_FileHandle_getMode(wasmu_Context* context);
    int dc_fs_FileHandle_isOpen(wasmu_Context* context);
    int dc_fs_FileHandle_isAvailable(wasmu_Context* context);
    int dc_fs_FileHandle_read(wasmu_Context* context);
    int dc_fs_FileHandle_readString(wasmu_Context* context);
    int dc_fs_FileHandle_write(wasmu_Context* context);
    int dc_fs_FileHandle_writeString(wasmu_Context* context);
    int dc_fs_FileHandle_getSize(wasmu_Context* context);
    int dc_fs_FileHandle_tell(wasmu_Context* context);
    int dc_fs_FileHandle_seek(wasmu_Context* context);
    int dc_fs_FileHandle_truncate(wasmu_Context* context);
    int dc_fs_FileHandle_start(wasmu_Context* context);
    int dc_fs_FileHandle_close(wasmu_Context* context);
    int dc_fs_DirectoryListing_new(wasmu_Context* context);
    int dc_fs_DirectoryListing_start(wasmu_Context* context);
    int dc_fs_DirectoryListing_next(wasmu_Context* context);
    int dc_fs_DirectoryListing_length(wasmu_Context* context);
    int dc_fs_open(wasmu_Context* context);
    int dc_fs_isFileOpen(wasmu_Context* context);
    int dc_fs_exists(wasmu_Context* context);
    int dc_fs_getEntryType(wasmu_Context* context);
    int dc_fs_remove(wasmu_Context* context);
    int dc_fs_rename(wasmu_Context* context);
    int dc_fs_createDirectory(wasmu_Context* context);
    int dc_fs_ensureParentDirectories(wasmu_Context* context);
    int dc_fs_listDirectory(wasmu_Context* context);
    int dc_test_TestClass_new(wasmu_Context* context);
    int dc_test_TestClass_identify(wasmu_Context* context);
    int dc_test_TestClass_add(wasmu_Context* context);
    int dc_test_TestClass_bools(wasmu_Context* context);
    int dc_test_TestClass_nextRandomNumber(wasmu_Context* context);
    int dc_test_TestClass_getString(wasmu_Context* context);
    int dc_test_TestClass_getChars(wasmu_Context* context);
    int dc_test_TestSubclass_new(wasmu_Context* context);
    int dc_test_TestSubclass_identify(wasmu_Context* context);
    int dc_test_TestSubclass_subclass(wasmu_Context* context);
    int dc_test_sayHello(wasmu_Context* context);
    int dc_test_add(wasmu_Context* context);
    int dc_test_getMostRecentTest(wasmu_Context* context);

    void linkFunctions(wasmu_Module* module);
}

#endif
